### PR TITLE
fix: special chars in subscriptions

### PR DESCRIPTION
**Pull request by ellite**

### CODE REVIEW

**Comment by ouuan** [comment]
By the way, it's usually better to escape data when displaying them instead of when saving them to the database. Then you won't ever need `htmlspecialchars_decode` and you can be sure that the data is escaped no matter what is stored in the database.

**Comment by ellite** [comment]
Hi @ouuan , thank you for the report.
Can you please give me a string that would trigger the XSS issue? I can't replicate it.
Regards.

**Comment by ouuan** [comment]
> Can you please give me a string that would trigger the XSS issue? I can't replicate it.

`` or `"><img src="" onerror="alert(2)`

**Comment by ellite** [comment]
Thanks. That one works.

**Comment by ellite** [comment]
2.29.2 released with a fix.
But I still need to cleanup a bit.

**Pull request merged**
