### PR TITLE
feat: add iCalendar Subscription

### PR DESCRIPTION
**Pull request by Qetesh**
I had the same need as [Wallos Issue #496](https://github.com/ellite/Wallos/issues/496). So, I added an iCalendar Subscription feature to support Apple Calendar and other calendar applications.

image

Let me know if any changes are needed. Thank you!

### CODE REVIEW

**Comment by httpsfelix** [comment]
How did you do that? 
I want to integreat my subscriptions to my getHomepage Dashboard with iCal but i dont know how to do that.

**Comment by ellite** [comment]
Hi @httpsfelix it is not live yet.
I will look at the PR after work today.

**Comment by Qetesh** [comment]
> How did you do that? I want to integreat my subscriptions to my getHomepage Dashboard with iCal but i dont know how to do that.

I use the test environment that is compatible with getHomepage, waiting for code merge.

image

**Review by ellite — APPROVED** [review]
Thanks.

**Pull request merged**
