### PR TITLE
Serbian translation

### PR DESCRIPTION
**Pull request by daVinci13**
Added Serbian translation in Cyrillic and Latin alphabet, and reduced the number of layers in Dockerfile.

### CODE REVIEW

**Comment by ellite** [comment]
Hi. Thank you for the contribution.

Could you please add:
```
If you want to contribute with a translation of wallos:

Add your language code to includes/i18n/languages.php in the format "en" => "English". Please use the original language name and not the english translation.
```

It's ordered alphabetically, so it should go between `"pt_br" => "Português Brasileiro"` and `"tr" => "Türkçe"`

Also, if you could change the version on includes/version.php to 1.20.0 I could merge direcly.

Thanks.

**Review by daVinci13 — COMMENTED** [review]
Edited pr as suggested! Keep up with good work!

**Review by ellite — APPROVED** [review]
Thank you.

**Comment by ellite** [comment]
Merged. Thanks.

**Pull request merged**
